config/routes.rb
Rails.application.routes.draw do

  get 'search/results'
  get 'tags/index'

  resources :replies

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users


# change post link to ex --> localhost:3000/the-godfather-part-one based off title of article

resources 'posts' do
  resources 'comments'
  resources 'images'
end


  root "welcome#index"
  # get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  acts_as_taggable_on :genre, :directed_by, :starring, :release_date, :general_tags # :rating, :media_type
  has_many :comments
  has_many :images
#  accepts_nested_attributes_for :images
  # has_many :images, through: :gallery


=begin
def movie_genres
  %w[Action Adventure Comedy Crime Drama Fantasy Historical Horror Mystery Paranoid Philosophical Political Romance Saga Satire Science_Fiction Thriller Western Animation ]
end

def type_of_media
  %w[ Movie Television Music]
end
=end

# Drop down form menus
# Rating
# Media Type

enum rating: {
  'G' => 0,
  'PG' => 1,
  'PG-13' => 2,
  'R' => 3,
  'NC-17' => 4
}

validates :rating, inclusion: ratings.keys # note the PLURAL version of ratings.keys

enum media_type: {
  'Movie' => 0,
  'TV Show' => 1,
  'Music' => 2
}

validates :media_type, inclusion: media_types.keys


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment_box_title = "Leave a Comment"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :author, :genre_list, :directed_by_list, :starring_list, :release_date_list, :general_tag_list, :rating, :producer, :media_type, :micro_review)
      # OLD PARAMS --> (:categories, :title, :ingredients, :content, :author, :prep_time, :cook_time, :yield, :directions, :tips, :rating, :category_list, :ingredient_list, :equipment_needed, :equipment_needed_list, :temp )
    end

    def change_comment_box_to_replies
      @comment_box_title = "Reply to"
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form-group">
    <%#= form.label :gallery %>
    <div class="gallery_form">

        <!-- Show / Remove Images -->
        <% if @post.images.any? %>

        <% @post.images.each do |image| %>

        <%= image_tag image.image_file.url(:thumb) %>
        <%= link_to 'X', post_image_path( post_id: @post.id, id: image.id, action: 'destroy' ), :method => :delete %>
                <%#= link_to 'X', post_image_path( post_id: @post.id, id: image.id, action: 'destroy' ), :method => :delete, data: { confirm: 'Are you sure?'} %>

        <% end %>

        <% end %>

    </div>
</div>

<%= form_with(model: post, local: true) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %>
        prohibited this post from being saved:</h2>

    <ul>
        <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: 'form-control' %>
</div>

<div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content, class: 'form-control', rows: 50, placeholder: 'html safe' %>
</div>

<div class="field">
<%= form.label :author %>
<%= form.text_field :author, id: :post_author, class: 'form-control' %>
</div>

<div class="field">
<%= form.label :producer %>
<%= form.text_field :producer, id: :post_producer, class: 'form-control' %>
</div>

<div class="field">
<%= form.label :micro_review %>
<%= form.text_field :micro_review, id: :post_micro_review, class: 'form-control' %>
</div>







<!-- TAGS START -->
<div class="form-group">
    <%= form.label :genre_list %>
    <%= form.text_area :genre_list , id: :post_genre_list, class: 'form-control' %>
</div>

<!-- MIGHT NEED TO CHANGE DIRECTED LIST LATER due to director being singular .. also rating and media_type -->
<div class="form-group">
    <%= form.label :directed_by_list %>
    <%= form.text_area :directed_by_list , id: :post_directed_by_list, class: 'form-control' %>
</div>

<div class="form-group">
    <%= form.label :starring_list %>
    <%= form.text_area :starring_list , id: :post_starring_list, class: 'form-control' %>
</div>

<div class="form-group">
    <%= form.label :release_date_list %>
    <%= form.text_area :release_date_list , id: :post_release_date_list, class: 'form-control' %>
</div>

<div class="form-group">
    <%= form.label :general_tag_list %>
    <%= form.text_area :general_tag_list , id: :post_general_tag_list, class: 'form-control' %>
</div>

<div class="form-group">
    <%= form.label :rating %>
    <%= form.select :rating, Post.ratings.keys,
                        prompt: 'Select a Rating',
                        class: 'form-control',
                        id: 'post_rating' %>
</div>

<div class="form-group">
    <%= form.label :media_type %>
    <%= form.select :media_type, Post.media_types.keys,
                                    prompt: 'Select a Media Type',
                                    id: :post_media,
                                    class: 'form-control' %>
</div>



<!-- TAGS END -->



<div class="form-group">
    <%= form.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>


<!-- Add additional images -->

<%= render 'shared/image_uploads' %>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
    <thead>
        <tr>
            <th>Categories</th>
            <th>Title</th>
            <th>Ingredients</th>
            <th>Content</th>
            <th>Author</th>
            <th>Prep time</th>
            <th>Cook time</th>
            <th>Yield</th>
            <th>Directions</th>
            <th>Tips</th>
            <th>Rating</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.categories %></td>
            <td><%= post.title %></td>
            <td><%= post.ingredients %></td>
            <td><%= post.content %></td>
            <td><%= post.author %></td>
            <td><%= post.prep_time %></td>
            <td><%= post.cook_time %></td>
            <td><%= post.yield %></td>
            <td><%= post.directions %></td>
            <td><%= post.tips %></td>
            <td><%= post.rating %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>




<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= provide(:application_head_content) do %>
<%= javascript_include_tag "commenting", "application" %>
<% end %>

<p id="notice"><%= notice %></p>

<h1><%= @post.title %></h1>
<p>
    <i>Uploaded
        <%= @post.created_at.strftime("%m/%d/%y") %> by <%= @post.author %></i>
</p>
<hr/>


<!-- Show Images -->
<% if @post.images.any? %>

<% @post.images.each_with_index do |image, index| %>
<!-- First image is used at the top as header -->
<% if index == 0 %>
<%= provide :large_top_image, (image_tag image.image_file.url(:large), class: 'center-block') %>
<% else %>
<!-- Remaining Images are placed at the bottom of the content -->
<%= provide :medium_bottom_image, (image_tag image.image_file.url(:medium)) %>
<% end %>

<% end %>

<% end %>


<%= yield :large_top_image %>


<p>
    <%= @post.content.html_safe %> <!-- .html_safe lets you render html from strings/text -->
</p>


<%= yield :medium_bottom_image %>





<table class="table">
    <tr>

        <!--
        <th>Prep Time</th>
        <th>Cook Time</th>
        <th>Yield</th> -->
    </tr>

    <tr>
        <!-- <td><%#= @post.prep_time %></td>
        <td><%#= @post.cook_time %></td>
        <td><%#= @post.yield %></td> -->
    </tr>
</table>

<!-- AD -->

<img src="http://placehold.it/336x280" class='center-block' >



<hr/>

<h1><%= @post.title %></h1>


<h4>Genre</h4>
<p><%= @post.genre_list %></p>
<h4>Directed By</h4>
<p><%= @post.directed_by_list %></p>
<h4>Starring</h4>
<p><%= @post.starring_list %></p>
<h4>Released</h4>
<p><%= @post.release_date_list %></p>
<h4>Tags</h4>
<p><%= @post.general_tag_list %></p>
<h4>Movie Rating</h4>
<p><%= @post.rating %></p>
<h4>Produced By</h4>
<p><%= @post.producer %></p>
<h4>Media Type</h4>
<p><%= @post.media_type %></p>
<h4>Micro Review</h4>
<p><%= @post.micro_review %></p>



<!--
<h3>Equipment Needed</h3>
<p>
    <%#= @post.equipment_needed_list %>
    <#% if @post.equipment_needed.any? %>
    <ul>
    <#% @post.equipment_needed.each do |item| %>
    <li><%#= item.name %></li>
    <#% end %>
    </ul>
    <#% end %>
</p>
-->



<!--
<h3>Ingredients</h3>
<p>
    <%#= @post.ingredient_list %>
</p>

<h3>Directions</h3>
<p>
    <%#= @post.directions.html_safe %>
</p>

<h4>Tips</h4>
<p>
    <%#= @post.tips.html_safe %>
</p>





<p>
    <strong>Tags:</strong>
    <%#= @post.category_list %>
</p>
-->



<!--
<p>
  <strong>Rating:</strong>
  <%#= @post.rating %>
</p> -->

<hr/>




<%#= render 'shared/comment_box' %>
<!-- COMMENT / REPLES START -->

<!-- Comment Box (Hide on reply) -->

<div id="comment-box">

<h1 id="comment-box-title"><%= @comment_box_title %></h1>
<%= form_for [@post, Comment.new] do |f| %>

<div class="row">


<div class="col-lg-8">

<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :comment_name, class: 'form-control' %>
</div>


<div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, id: :comment_email, class: 'form-control email' %>
</div>

<div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, id: :comment_website, class: 'form-control url' %>
</div>

<div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, id: :comment_rating, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, id: :comment_comment, class: 'form-control', rows: 5 %>
</div>

<div class="form-group">
    <%= f.label :email_notification, class: 'form-check-label' %>
    <%= f.check_box :email_notification, id: :comment_email_notification, class: 'form-check-input' %>
</div>

<%= f.submit 'Add Comment' %>


</div> <!-- ./col-lg-6 -->

</div> <!-- ./row -->
<% end %>
</div><!-- ./comment-box -->



















<!-- COMMENT / REPLIES END -->

<% if @post.comments.any? %>

<h1>Comments</h1>

<% @post.comments.each do |comment| %>
<div class="comment">
<h4><%= comment.name %></h4>
<p><i><%= comment.created_at.strftime("%m/%d/%y") %></i></p>
<p>Rating: <%= comment.rating %></p>
<p><%= comment.comment %></p>

<!-- <p class="reply-to-button">Reply</p> -->


</div><!-- ./comment -->

<% end %>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %>
|
<%= link_to 'Back', posts_path %>